name : "Hello world workflow"

# Controls when the action will run. Triggers the workflow on push some to master branch or production branch
on:
  push:
    branches:
      - master
      - production

jobs:
  hello_word:
    runs-on: ubantu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World"

      - name: "Print current date"
        run: date